# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='usuario')),
                ('person_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='apellido')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email alternativo')),
                ('office', models.CharField(blank=True, max_length=200, null=True, verbose_name='oficina')),
                ('other_office', models.CharField(blank=True, max_length=200, null=True, verbose_name='otra oficina')),
                ('group_id', models.CharField(blank=True, max_length=200, null=True)),
                ('document_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='nro documento')),
                ('type_document_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='tipo documento')),
                ('country_document_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='nro documento pa\xeds')),
                ('telephone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='tel\xe9fono laboral')),
                ('home_telephone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='tel\xe9fono personal')),
                ('floor', models.CharField(blank=True, max_length=200, null=True, verbose_name='piso')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='area')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Persona Ldap',
                'managed': True,
                'verbose_name_plural': 'Personas Ldap',
            },
        ),
    ]
