# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0002_create_model_ldap_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'offices',
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
    ]
