# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0003_create_model_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapperson',
            options={'managed': False, 'verbose_name': 'Persona Ldap', 'verbose_name_plural': 'Personas Ldap'},
        ),
    ]
