# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0004_change_meta_on_ldapperson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ldapperson',
            table='ldap_people_ldapperson',
        ),
    ]
