# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0006_add_field_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'db_table': 'ldap_people_ldapoffices',
                'verbose_name': 'LdapOffice',
                'verbose_name_plural': 'LdapOffices',
            },
        ),
    ]
