# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0007_create_model_ldapoffice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapoffice',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
    ]
