# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_people', '0008_office_not_required_in_admin_form'),
    ]
    operations = [
        migrations.RunSQL("ALTER TABLE ldap_people_ldapperson ADD COLUMN info varchar(500);",
                      "ALTER TABLE ldap_people_ldapperson DROP COLUMN info;"),
    ]
