# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_table_ldap_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapperson',
            options={'managed': False, 'verbose_name': 'Persona Ldap', 'verbose_name_plural': 'Personas Ldap'},
        ),
    ]
