# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_model_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapperson',
            options={'managed': False, 'verbose_name': 'Persona Ldap', 'verbose_name_plural': 'Personas Ldap'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
    ]
