# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_change_meta_options_on_ldapperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Grupo',
                'managed': False,
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
