# -*- coding: utf-8 -*-

from __future__ import unicode_literals

"""
Django settings for shoal project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import ast
import environ
import logging
import os
import ldap
from django.utils.translation import ugettext_lazy as _
from django.conf.locale.es import formats as es_formats
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#env = environ.Env(
    # set casting, default value
#    DEBUG=(bool, False)
#)
#environ.Env.read_env()

BASE_URL = os.environ.get('BASE_URL')
APPLICATION_NAME = os.environ.get('APPLICATION_NAME')
APPLICATION_DESC = os.environ.get('APPLICATION_DESC')

es_formats.DATETIME_FORMAT = "d-m-Y H:i"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Nivel mínimo para registrar eventos (cubre DEBUG, INFO, WARNING, ERROR)
LOGGING_DEBUG = os.getenv("LOGGING_DEBUG", "DEBUG") == "DEBUG"

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS')

ADMINS=os.environ.get('ADMINS')

MANAGERS= os.environ.get('MANAGERS')

# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'jquery_ui',
    'bootstrap_ui',
    'django_extensions',
    'bootstrap_themes',
    'app',
    'ldap_people',
]

MIDDLEWARE = [
    'app.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'app.middleware.ForceLangMiddleware',
]

ROOT_URLCONF = 'shoal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'ldap_people/templates'),
                 os.path.join(BASE_DIR, 'password_change/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.enable_user_password_change',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD':  os.environ.get('DB_USER_PASSWORD'),
        'PORT': os.environ.get('DB_PORT'),
        'HOST': os.environ.get('DB_HOST'),
    },
    'db_owner': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_OWNER'),
        'PASSWORD': os.environ.get('DB_OWNER_PASSWORD'),
        'PORT': os.environ.get('DB_PORT'),
        'HOST': os.environ.get('DB_HOST'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE')
LANGUAGES = (
  ('es', _('Spanish')),
  ('en', _('English')),
)
LOCALE_PATHS = [
    os.path.join(os.environ.get('CONTEXT_PATH'), '/shared/app/locale/'),
    os.path.join(BASE_DIR, 'locale/'),
]

TIME_ZONE = os.environ.get('TIME_ZONE')

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_CHARSET = os.environ.get('DEFAULT_CHARSET')

LOGIN_URL = os.environ.get('LOGIN_URL')

LOGIN_REDIRECT_URL = os.environ.get('LOGIN_REDIRECT_URL')

STATIC_ROOT = os.environ.get('STATIC_ROOT')
STATIC_URL = os.environ.get('STATIC_URL')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# django configuration
SUIT_CONFIG = {
    'ADMIN_NAME': APPLICATION_NAME
}

# Configurar backend de sesion en archivos o base de datos
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
#SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Definir ubicacion de archivos de sesion si se opto por
# django.contrib.sessions.backends.file
SESSION_FILE_PATH = "/srv/django_sessions"

SESSION_COOKIE_NAME = os.environ.get('SESSION_COOKIE_NAME')
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE',1209600))
SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN')
SESSION_SAVE_EVERY_REQUEST = bool(os.getenv('SESSION_SAVE_EVERY_REQUEST',True))

# =================================\
# ldap configuration
LDAP_SERVER = os.environ.get('LDAP_SERVER')

# DN y usuario donde hace el bind la aplicaccion
# requiere permisos para la gestion y modificacion
# de usuarios en ldap
# Los usuarios que gestiona son los indicados en
# LDAP_DN_USERS, y gestiona los grupos de dichos
# usuarios indicados en LDAP_DN_GROUP
LDAP_BIND_DN=os.environ.get('LDAP_BIND_DN')
LDAP_BIND_USERNAME=os.environ.get('LDAP_BIND_USERNAME')
LDAP_BIND_PASSWORD=os.environ.get('LDAP_BIND_PASSWORD')

# DN para autenticacion de usuarios desde django
# LDAP_DN_AUTH: Donde busca los usuarios que se loguean
# Con LDAP_DN_AUTH_USERS: Donde autentica los usuarios que se loguean 
# con LDAP_DN_AUTH_GROUP: Donde obtiene permisos de grupo de los usuarios
#LDAP_DN_AUTH = os.environ.get('LDAP_DN_AUTH')
LDAP_DN_AUTH_USERS = os.environ.get('LDAP_DN_AUTH_USERS')
LDAP_DN_AUTH_GROUP = os.environ.get('LDAP_DN_AUTH_GROUP')

# LDAP_DN_USERS: Donde obtiene usuarios para armar el listado telefonico
LDAP_DN_USERS = os.environ.get('LDAP_DN_USERS')

LDAP_GROUP_FIELDS  = ast.literal_eval(os.environ.get('LDAP_GROUP_FIELDS'))  # id first!
LDAP_PEOPLE_FIELDS = ast.literal_eval(os.environ.get('LDAP_PEOPLE_FIELDS')) # idfirst!

#
# Maximum limit of results to be taken as error
LDAP_SIZE_LIMIT = int(os.environ.get('LDAP_SIZE_LIMIT'))
#
# If specified, add the ObjectClass to the search condition of ldap
LDAP_FILTER_OBJECT_CLASS = ast.literal_eval(os.environ.get('LDAP_FILTER_OBJECT_CLASS'))
#
# If specified, add the ObjectClass to the search condition of ldap
LDAP_FILTER_MEMBERS_OUT_OF_GROUPS = ast.literal_eval(os.environ.get('LDAP_FILTER_MEMBERS_OUT_OF_GROUPS'))
#
# Enable password change functionality
ENABLE_ADMIN_PASSWORD_CHANGE = os.environ.get('ENABLE_ADMIN_PASSWORD_CHANGE')
#
# Enable password change functionality
ENABLE_USER_PASSWORD_CHANGE = os.environ.get('ENABLE_USER_PASSWORD_CHANGE')
#
# restricts the password change functionality
# for users who are in the indicated groups
RESTRICT_PASSWORD_CHANGE_TO_GROUPS = ast.literal_eval(os.environ.get('RESTRICT_PASSWORD_CHANGE_TO_GROUPS'))
#
# Domain name used to identify the institutional mail of an alternative
# Ej: the (LDAP DN)
LDAP_DOMAIN_MAIL = os.environ.get('LDAP_DOMAIN_MAIL')

# Performs filtering to obtain LDAP groups
# min group_id (group_id>= 500) for ldap search filter
LDAP_GROUP_MIN_VALUE = int(os.environ.get('LDAP_GROUP_MIN_VALUE'))
#
# group_id to exclude in ldap search filter
LDAP_GROUP_SKIP_VALUES = ast.literal_eval(os.environ.get('LDAP_GROUP_SKIP_VALUES'))

# Shows additional information in the search if the registered user
# belongs to any of the indicated groups
GROUPS_EXTRA_INFORMATION_SEARCH = ast.literal_eval(os.environ.get('GROUPS_EXTRA_INFORMATION_SEARCH'))
#
# Password length used by default in password change functionality
DEFAULT_PASSWORD_LENGHT = int(os.environ.get('DEFAULT_PASSWORD_LENGHT'))
# =================================/

# =================================\
# django ldap configuration
#
#
# Ldap Group Type
from django_auth_ldap.config import LDAPSearch, PosixGroupType

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(LDAP_DN_AUTH_GROUP,
                                    ldap.SCOPE_SUBTREE, "(objectClass=posixGroup)"
)
AUTH_LDAP_GROUP_TYPE =  PosixGroupType()
#
#
# User will be updated with LDAP every time the user logs in.
# Otherwise, the User will only be populated when it is automatically created.
AUTH_LDAP_ALWAYS_UPDATE_USER = True
#
#
# Simple group restrictions
# AUTH_LDAP_REQUIRE_GROUP = "cn=users,ou={},{}".format(LDAP_GROUP,LDAP_DN)
# AUTH_LDAP_DENY_GROUP = "cn=denygroup,ou={},{}".format(LDAP_GROUP,LDAP_DN)
#
# Defines the django admin attribute
# according to whether the user is a member or not in the specified group
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=users,{}".format(LDAP_DN_AUTH_GROUP),
    "is_staff": "cn=users,{}".format(LDAP_DN_AUTH_GROUP),
    "is_superuser": "cn=admin,{}".format(LDAP_DN_AUTH_GROUP),
}
#
# Ldap User Auth
AUTH_LDAP_BIND_DN = "cn={},{}".format(LDAP_BIND_USERNAME,LDAP_BIND_DN)
AUTH_LDAP_BIND_PASSWORD = LDAP_BIND_PASSWORD

AUTH_LDAP_SERVER_URI = LDAP_SERVER

AUTH_LDAP_USER_SEARCH = LDAPSearch(LDAP_DN_AUTH_USERS,
                                   ldap.SCOPE_SUBTREE, "(uid=%(user)s)")
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# =================================/

#loggin querys in develompent
# if DEBUG:
#     l = logging.getLogger('django.db.backends')
#     l.setLevel(logging.DEBUG)
#     l.addHandler(logging.StreamHandler())
#     logging.basicConfig(
#         level = logging.DEBUG,
#         format = " %(levelname)s %(name)s: %(message)s",
#     )


# logger = logging.getLogger('django_auth_ldap')
# logger.addHandler(logging.StreamHandler())
# logger.setLevel(logging.DEBUG)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console_stdout': {
            'level': LOGGING_DEBUG,  # Puedes ajustar el nivel de log según tus necesidades
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,  # Enviar mensajes de log a stdout
        },
        'console_stderr': {
            'level': LOGGING_DEBUG,
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,  # Enviar errores a stderr
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console_stdout', 'console_stderr'],
            'level': LOGGING_DEBUG,  # Nivel mínimo para registrar eventos (cubre DEBUG, INFO, WARNING, ERROR)
            'propagate': True,
        },
        'django.contrib.sessions': {
            'handlers': ['console_stdout', 'console_stderr'],
            'level': LOGGING_DEBUG,
            'propagate': False,
        },
    },
}
